### PR TITLE
Add Credit/Debit Notes manual.

### PR DESCRIPTION
**Pull request by pavel-mironchik**

### CODE REVIEW

**Comment by pavel-mironchik** [comment]
Is this fine that I added so many screenshots?

**Comment by denisdulici** [comment]
> Is this fine that I added so many screenshots?

More than ok 😉

**Comment by denisdulici** [comment]
Is this ready to merge?

**Comment by pavel-mironchik** [comment]
Yes, absolutely. Just was waiting till the application release and wasn't totally sure there will not be some changes until then.

**Pull request merged**
